from enum import Enum
from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


class AgentName(str, Enum):
    """Centralized enum for agent names to avoid magic strings.

    These names must match the node names registered in the LangGraph workflow.
    """
    # Analyst Team
    MARKET_ANALYST = "Market Analyst"
    SENTIMENT_ANALYST = "Sentiment Analyst"
    NEWS_ANALYST = "News Analyst"
    FUNDAMENTALS_ANALYST = "Fundamentals Analyst"

    # Research Team
    BULL_RESEARCHER = "Bull Researcher"
    BEAR_RESEARCHER = "Bear Researcher"
    RESEARCH_MANAGER = "Research Manager"

    # Trading Team
    TRADER = "Trader"

    # Risk Management Team
    AGGRESSIVE_ANALYST = "Aggressive Analyst"
    CONSERVATIVE_ANALYST = "Conservative Analyst"
    NEUTRAL_ANALYST = "Neutral Analyst"

    # Portfolio Management
    PORTFOLIO_MANAGER = "Portfolio Manager"

    # Message clearing nodes (internal)
    MSG_CLEAR_MARKET = "Msg Clear Market"
    MSG_CLEAR_SENTIMENT = "Msg Clear Sentiment"
    MSG_CLEAR_NEWS = "Msg Clear News"
    MSG_CLEAR_FUNDAMENTALS = "Msg Clear Fundamentals"

    # Tool nodes (internal)
    TOOLS_MARKET = "tools_market"
    TOOLS_SOCIAL = "tools_social"
    TOOLS_NEWS = "tools_news"
    TOOLS_FUNDAMENTALS = "tools_fundamentals"


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
